event_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import home

urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('events/', include('events.urls')),
]

events/urls.py
from django.urls import path
from events.views import dashboard, create_event, update_event, view_events, view_event_details, delete_event, create_participant, view_participant, update_participant, delete_participant
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('dashboard/', dashboard, name='dashboard'),
    path('create-event/', create_event, name="create-event"),
    path('update-event/<int:id>', update_event, name="update-event"),
    path('view-all-events/', view_events, name='view-events'),
    path('view-event-details/<int:id>/', view_event_details, name='view-event-details'),
    path('delete-event/<int:id>', delete_event, name='delete-event'),
    path('register-participant/event-id=<int:id>', create_participant, name='register-participant'),
    path('view-participants/', view_participant, name='view-participants'),
    path('update-participant/<int:id>', update_participant, name='update-participant'),
    path('delete-participant/<int:id>', delete_participant, name='delete-participant'),
] + debug_toolbar_urls()

events/models.py
from django.db import models
import datetime

# Create your models here.
class Participant(models.Model):
    participant_name = models.CharField(max_length=100, null=False)
    participant_email = models.EmailField(null=False)
    registered_event = models.ManyToManyField("Event", related_name="registered_event")

class Category(models.Model):
    TODAY = "TODAY"
    UPCOMING = "UPCOMING"
    PAST = "PAST"

    EVENT_CATEGORY = (
        (TODAY, "Today's Event"),
        (UPCOMING, "Upcoming Event"),
        (PAST, 'Past Event')
    )

    category_name = models.CharField(max_length=50, choices=EVENT_CATEGORY, null=False, default=TODAY)
    category_description = models.TextField()

class Event(models.Model):
    name = models.CharField(max_length=100, null=False)
    description = models.TextField(null=False)
    date = models.DateField(default=datetime.date.today, blank=False, null=False)
    time = models.CharField(max_length=50, blank=False, null=False)
    location = models.CharField(max_length=100, null=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="category")

events/forms.py
from django import forms
from events.models import Event, Category, Participant

class EventModelForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['name', 'description', 'date', 'time', 'location']
        labels = {
            'name': '',
            'description': '',
            'location': '',
            'date': 'Select Event Date'
        }
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'px-4 py-4 rounded-md w-full bg-[#E6F0F0] focus:outline-none focus:border-none',
                'placeholder': 'e.g. Festival',
                'type': 'text',
            }),
            'description': forms.Textarea(attrs={
                'class': 'px-4 py-4 rounded-md w-full bg-[#E6F0F0] focus:outline-none focus:border-none',
                'placeholder': 'Describe about the event',
            }),
            'date': forms.DateInput(
                format="%Y-%m-%d",
                attrs={
                    'class': 'bg-[#E6F0F0] px-4 py-4 rounded-md',
                    'type': 'date',
                }, 
            ),
            'time': forms.TimeInput(attrs={
                'class': 'bg-[#E6F0F0] px-4 py-4 rounded-md',
                'type': 'time',
            }),
            'location': forms.TextInput(attrs={
                'class': 'px-4 py-4 rounded-md w-full bg-[#E6F0F0] focus:outline-none focus:border-none',
                'placeholder': 'Enter event location',
                'type': 'text',
            }),
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date'].input_formats = ['%Y-%m-%d']

class CategoryModelForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['category_name']
        labels = {
            'category_name': 'Category',
        }
        widgets = {
            'category_name': forms.Select(attrs={
                'class': 'bg-[#E6F0F0] px-4 py-4 rounded-md border-r-[16px] border-[#E6F0F0]',
            }),
        }

class ParticipantModelForm(forms.ModelForm):
    class Meta:
        model = Participant
        fields = ['participant_name', 'participant_email']
        labels = {
            'participant_name': 'Your Full Name',
            'participant_email': 'Your Email Address',
        }
        widgets = {
            'participant_name': forms.TextInput(
                attrs = {
                    'class': 'px-4 py-4 rounded-md w-full bg-[#E6F0F0] focus:outline-none focus:border-none',
                    'placeholder': 'Describe about the event',
                    'type': 'text',
                    'placeholder': 'e.g. John Doe'
                }
            ),
            'participant_email': forms.EmailInput(
                attrs = {
                    'class': 'px-4 py-4 rounded-md w-full bg-[#E6F0F0] focus:outline-none focus:border-none',
                    'placeholder': 'Describe about the event',
                    'type': 'email',
                    'placeholder': 'e.g name@gmail.com'
                }
            )
        }

events/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from events.forms import EventModelForm, CategoryModelForm, ParticipantModelForm
from events.models import Event, Category, Participant
from django.contrib import messages
from django.db.models import Count, Q
from django.utils import timezone

# Create your views here.

def dashboard(request):
    type = request.GET.get('type', '')
    # events = Event.objects.prefetch_related('registered_event').all()

    # Get Today's Events
    today = timezone.now().date()
    todays_events = Event.objects.filter(date=today)

    counts = Event.objects.aggregate(
        total_participant=Count('registered_event', distinct=True),
        total_events=Count('id', distinct=True),
        total_upcoming=Count('id', filter=Q(category__category_name='UPCOMING'), distinct=True),
        total_past=Count('id', filter=Q(category__category_name='PAST'), distinct=True),
    )

    BASE_QUERY = Event.objects.select_related('category').all()

    if type == 'upcoming':
        events = BASE_QUERY.filter(category__category_name='UPCOMING')
    elif type == 'past':
        events = BASE_QUERY.filter(category__category_name='PAST')
    elif type == 'total-event':
        events = BASE_QUERY.all()
    else:
        events = todays_events
        

    context = {
        "counts": counts,
        'events': events,
    }

    return render(request, 'pages/dashboard.html', context=context)

# Create event
def create_event(request):
    if request.method == 'POST':
        event_model_form = EventModelForm(request.POST, prefix="event")
        category_model_form = CategoryModelForm(request.POST, prefix="category")

        if event_model_form.is_valid() and category_model_form.is_valid():
            category_instance = category_model_form.save()
            
            event_instance = event_model_form.save(commit=False)
            event_instance.category = category_instance
            event_instance.save()

            event_model_form.save_m2m()

            messages.success(request, 'Event created successfully')

        else:
            messages.error(request, 'Something went wrong! Check your inputs')

    else:
        event_model_form = EventModelForm(prefix="event")
        category_model_form = CategoryModelForm(prefix="category")

    context = {
        'event_form': event_model_form,
        'category_form': category_model_form,
    }

    return render(request, 'pages/create-event.html', context=context)

def update_event(request, id):
    event = Event.objects.get(id=id)
    event_form = EventModelForm(instance=event)

    try:
        event_category = event.category
    except Category.DoesNotExist:
        event_category = None
    
    category_form = CategoryModelForm(instance=event_category)

    if request.method == 'POST':
        event_form = EventModelForm(request.POST, instance=event)
        category_form = CategoryModelForm(request.POST, instance=event_category)

        if event_form.is_valid() and category_form.is_valid():
            saved_category = category_form.save()

            updated_event = event_form.save(commit=False)
            updated_event.category = saved_category
            updated_event.save()

            messages.success(request, "Event updated successfully!")

        else:
            messages.error(request, "Something went wrong! Try again later")
    
    return render(request, 'pages/update-event.html', {
        'event_form': event_form,
        'category_form': category_form,
        'event': event,
    })

def view_events(request):
    type = request.GET.get('type', '')

    start_date = request.GET.get('start_date')
    end_date = request.GET.get('end_date')

    search_query = request.GET.get('search', '').strip()
    
    BASE_QUERY = Event.objects.select_related('category').prefetch_related('registered_event').annotate(total_participants=Count('registered_event'))

    if type == 'today':
        events = BASE_QUERY.filter(date=timezone.now().date())
    elif type == 'upcoming':
        events = BASE_QUERY.filter(category__category_name='UPCOMING')
    elif type == 'past':
        events = BASE_QUERY.filter(category__category_name='PAST')
    else:
        events = BASE_QUERY.all()

    if start_date and end_date:
        events = BASE_QUERY.filter(date__gte=start_date, date__lte=end_date)

    if search_query:
        events = BASE_QUERY.filter(
            Q(name__icontains=search_query) |
            Q(location__icontains=search_query)
        )

    return render(request, 'pages/view-all-events.html', context={
        'events': events,
    })

def delete_event(request, id):
    if request.method == 'POST':
        event = Event.objects.get(id=id)
        event.delete()
        
        return redirect('view-events')
    else:
        return redirect('view-events')

# Event details
def view_event_details(request, id):
    # event = Event.objects.get(id=id)
    event = Event.objects.prefetch_related('registered_event').get(id=id)

    similar_events = (
        Event.objects
        .filter(date=event.date)
        .exclude(id=event.id)
        .select_related('category')
    )

    return render(request, 'pages/view-event-details.html', context={
        'event': event,
        'similar_events': similar_events,
    })

# Create Perticipant
def create_participant(request, id):
    event = Event.objects.get(id=id)

    if request.method == 'POST':
        participant_form = ParticipantModelForm(request.POST)
        if participant_form.is_valid():
            email = participant_form.cleaned_data['participant_email']
            name = participant_form.cleaned_data['participant_name']

            participant, created = Participant.objects.get_or_create(
                participant_email=email,
                participant_name=name,
            )

            if event in participant.registered_event.all():
                messages.warning(request, 'You are already registered for this event.')
            else:
                participant.registered_event.add(event)
                messages.success(request, 'Registration Successful!')
    else:
        participant_form = ParticipantModelForm()

    return render(request, 'pages/create-participant.html', {
        'participant_form': participant_form,
        'event': event,
    })

def view_participant(request):
    participants = Participant.objects.prefetch_related('registered_event').all()

    return render(request, 'pages/view-participants.html', {'participants': participants})

def update_participant(request, id):
    participant = Participant.objects.get(id=id)

    if request.method == 'POST':
        participant_form = ParticipantModelForm(request.POST, instance=participant)

        if participant_form.is_valid():
            participant_form.save()
            messages.success(request, 'Update successful')
        else:
            messages.error(request, 'Something went wrong! Try again later')
    else:
        participant_form = ParticipantModelForm(instance=participant)

    return render(request, 'pages/update-participant.html', {
        'participant_form': participant_form
    })

def delete_participant(request, id):
    if request.method == 'POST':
        participant = Participant.objects.get(id=id)
        participant.delete()
        
        return redirect('view-participants')
    else:
        return redirect('view-participants')

events/templates/pages/create-event.html
{% extends "index.html" %} 

{% block templates %}
  <div>
    {% comment %} Messages container {% endcomment %}
    <div>
      {% if messages %}
        {% for message in messages %}
          <p class="
          {% if message.tags == 'success' %}
            bg-green-400
          {% else %}
            bg-red-400
          {% endif %} text-white m-4 p-4 rounded-md text-center font-bold text-xl">{{ message }}</p>
        {% endfor %}
      {% endif %}
    </div>
    {% comment %} Form container {% endcomment %}
     <div>
       <h1 class="text-2xl font-semibold text-center leading-relaxed my-12">CREATE A EVENT</h1>
       <form method="POST" class="w-1/2 mx-auto flex flex-col gap-4 ">
        {% csrf_token %}
        <div class="w-full flex flex-col gap-2">
          <p class="font-medium leading-relaxed">Event Name:</p>
          {{ event_form.name }}
        </div>
        <div class="flex flex-col gap-2">
          <p class="font-medium leading-relaxed">Select Event Date:</p>
          {{ event_form.date }}
        </div>
        <div class="flex flex-col gap-2">
          <p class="font-medium leading-relaxed">Event Time:</p>
          {{ event_form.time }}
        </div>
        <div class="flex flex-col gap-2">
          <p class="font-medium leading-relaxed">Location:</p>
          {{ event_form.location }}
        </div>
        <div class="flex flex-col gap-2">
          <p class="font-medium leading-relaxed">Category:</p>
          {{ category_form.category_name }}
        </div>
        <div class="flex flex-col gap-2">
          <p class="font-medium leading-relaxed">Describe the Event:</p>
          {{ event_form.description }}
        </div>
        <button
            class="bg-green-400 hover:bg-green-700 text-white px-4 py-4 rounded-md mt-2"
            type="submit"
          >
            Submit
          </button>
      </form>
     </div>
  </div>
{% endblock templates %}

events/templates/pages/create-participant.html
{% extends "index.html" %}

{% block templates %}
<div>
  {% comment %} Messages container {% endcomment %}
  <div>
    {% if messages %}
      {% for message in messages %}
        <p class="
        m-4 p-4 rounded-md text-center font-bold text-xl text-white
        {% if message.tags == 'success' %}
          bg-green-400
        {% elif message.tags == 'error' %}
          bg-red-400 
        {% elif message.tags == 'warning' %}
          bg-orange-400
        {% endif %}
        ">
        {{ message }}
        </p>
      {% endfor %}
    {% endif %}
  </div>
  {% comment %} Form container {% endcomment %}
   <div>
     <h1 class="text-2xl font-semibold text-center leading-relaxed my-12">REGISTER FOR THE EVENT</h1>
     <form method="POST" class="w-1/2 mx-auto flex flex-col gap-4 ">
      {% csrf_token %}
      <div class="w-full flex flex-col gap-2">
        <p class="font-medium leading-relaxed">Your Full Name</p>
        {{ participant_form.participant_name }}
      </div>
      <div class="flex flex-col gap-2">
        <p class="font-medium leading-relaxed">Email Address</p>
        {{ participant_form.participant_email }}
      </div>
      <button
          class="bg-green-400 hover:bg-green-700 text-white px-4 py-4 rounded-md mt-2"
          type="submit"
        >
          Register
        </button>
    </form>
   </div>
</div>
{% endblock templates %}

events/templates/pages/dashboard.html
{% extends "index.html" %}

{% block templates %}
  <section>
    {% comment %} Counts {% endcomment %}
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
      <a>
        <div class="bg-red-200 text-center rounded-md p-6">
          <h1>Total Number of participants</h1>
          <p class="font-bold text-4xl mt-4">{{ counts.total_participant }}</p>
        </div>
      </a>
      <a href="{% url "dashboard" %}?type=total-event">
        <div class="bg-green-200 text-center rounded-md p-6">
          <h1>Total Number of events</h1>
          <p class="font-bold text-4xl mt-4">{{ counts.total_events }}</p>
        </div>
      </a>
      <a href="{% url "dashboard" %}?type=upcoming">
        <div class="bg-blue-200 text-center rounded-md p-6">
          <h1>Upcoming events</h1>
          <p class="font-bold text-4xl mt-4">{{ counts.total_upcoming }}</p>
        </div>
      </a>
      <a href="{% url "dashboard" %}?type=past">
        <div class="bg-yellow-200 text-center rounded-md p-6">
          <h1>Past events</h1>
          <p class="font-bold text-4xl mt-4">{{ counts.total_past }}</p>
        </div>
      </a>
    </div>
    {% comment %} Table {% endcomment %}
    <div class="mt-12">
      <div class="relative overflow-x-auto">
        <table class="w-full text-sm text-left text-gray-500">
          <thead class="text-xs text-gray-700 uppercase bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3">
                Event Name
              </th>
              <th scope="col" class="px-6 py-3">
                Date
              </th>
              <th scope="col" class="px-6 py-3">
                Time
              </th>
              <th scope="col" class="px-6 py-3">
                Location
              </th>
            </tr>
          </thead>
          <tbody>
            {% for p in events %}
              <tr class="bg-white border-b border-gray-200">
                <td scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                    {{ p.name }}
                </td>
                <td class="px-6 py-4">
                    {{ p.date }}
                </td>
                <td class="px-6 py-4">
                  {{ p.time }}
                </td>
                <td class="px-6 py-4">
                  {{ p.location }}
                </td>
              </tr>
            {% empty %}
              <tr>
                <td colspan="4" class="px-6 py-4 text-center text-gray-500">
                    No participants are joining this event.
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>
{% endblock templates %}

events/templates/pages/update-event.html
{% extends "index.html" %}

{% block templates %}
  <div>
    {% comment %} Messages container {% endcomment %}
    <div>
      {% if messages %}
        {% for message in messages %}
          <p class="
          {% if message.tags == 'success' %}
            bg-green-400
          {% else %}
            bg-red-400
          {% endif %} text-white p-4 rounded-md text-center font-bold text-xl w-full">{{ message }}</p>
        {% endfor %}
      {% endif %}
    </div>
    <div>
      {% if messages %}
        {% for message in messages %}
        <a 
          class="{% if message.tags == 'success' %} block {% else %} hidden {% endif %} w-full text-center mt-6 p-2 bg-orange-300 rounded-md" 
          href="{% url 'view-event-details' event.id %}">
          Check Updated Details
        </a>
        {% endfor %}
      {% endif %}
    </div>
    {% comment %} Form container {% endcomment %}
     <div>
       <h1 class="text-2xl font-semibold text-center leading-relaxed my-12">UPDATE THE EVENT</h1>
       <form method="POST" class="mx-auto flex flex-col gap-4 ">
        {% csrf_token %}
        <div class="w-full flex flex-col gap-2">
          <p class="font-medium leading-relaxed">Event Name:</p>
          {{ event_form.name }}
        </div>
        <div class="flex flex-col gap-2">
          <p class="font-medium leading-relaxed">Select Event Date:</p>
          {{ event_form.date }}
        </div>
        <div class="flex flex-col gap-2">
          <p class="font-medium leading-relaxed">Event Time:</p>
          {{ event_form.time }}
        </div>
        <div class="flex flex-col gap-2">
          <p class="font-medium leading-relaxed">Location:</p>
          {{ event_form.location }}
        </div>
        <div class="flex flex-col gap-2">
          <p class="font-medium leading-relaxed">Category:</p>
          {{ category_form.category_name }}
        </div>
        <div class="flex flex-col gap-2">
          <p class="font-medium leading-relaxed">Describe the Event:</p>
          {{ event_form.description }}
        </div>
        <button
            class="bg-green-400 hover:bg-green-700 text-white px-4 py-4 rounded-md mt-2"
            type="submit"
          >
            Update
          </button>
      </form>
     </div>
  </div>
{% endblock templates %}

events/templates/pages/update-participant.html
{% extends "index.html" %}

{% block templates %}
<div>
  {% comment %} Messages container {% endcomment %}
  <div>
    {% if messages %}
      {% for message in messages %}
        <p class="
        m-4 p-4 rounded-md text-center font-bold text-xl text-white
        {% if message.tags == 'success' %}
          bg-green-400
        {% elif message.tags == 'error' %}
          bg-red-400 
        {% endif %}
        ">
        {{ message }}
        </p>
      {% endfor %}
    {% endif %}
  </div>
  {% comment %} Form container {% endcomment %}
   <div>
     <h1 class="text-2xl font-semibold text-center leading-relaxed my-12">UPDATE PARTICIPANT INFORMATION</h1>
     <form method="POST" class="w-1/2 mx-auto flex flex-col gap-4 ">
      {% csrf_token %}
      <div class="w-full flex flex-col gap-2">
        <p class="font-medium leading-relaxed">Your Full Name</p>
        {{ participant_form.participant_name }}
      </div>
      <div class="flex flex-col gap-2">
        <p class="font-medium leading-relaxed">Email Address</p>
        {{ participant_form.participant_email }}
      </div>
      <button
          class="bg-green-400 hover:bg-green-700 text-white px-4 py-4 rounded-md mt-2"
          type="submit"
        >
          Update
        </button>
    </form>
   </div>
</div>
{% endblock templates %}

events/templates/pages/view-all-events.html
{% extends "index.html" %}
{% load static %}

{% block templates %}
  <section>
    {% comment %} Event banner design {% endcomment %}
    {% comment %} Filtering Options {% endcomment %}
    <div class="flex flex-col lg:flex-row justify-between lg:items-end">
      <div class="mb-8">
        <p class="font-bold mb-2">SORT BY</p>
  
        <form class="inline" action="{% url 'view-events' %}">
          <select class="text-sm bg-black/5 px-4 py-4 text-md rounded-md border-r-8 border-transparent w-full lg:w-auto" name="type" id="event-filter" onchange="this.form.submit()">
            <option value="all" {% if request.GET.type == "all" %}selected{% endif %}>All</option>
            <option value="today" {% if request.GET.type == "today" %}selected{% endif %}>Today</option>
            <option value="upcoming" {% if request.GET.type == "upcoming" %}selected{% endif %}>Upcoming</option>
            <option value="past" {% if request.GET.type == "past" %}selected{% endif %}>Past</option>
          </select>
        </form>
        
        <p class="mt-4 font-bold">OR</p>
  
        <form class="flex flex-col gap-2 lg:flex-row lg:items-center mt-2" action="{% url 'view-events' %}">
          <!-- Date range filters -->
          <label class="font-bold" for="start_date">Start Date:</label>
          <input class="bg-black/5 px-4 py-4 rounded-md text-sm" type="date" name="start_date" value="{{ request.GET.start_date }}" class="px-4 py-2 rounded-md border mb-4" required />
          <label class="font-bold" for="end_date">End Date:</label>
          <input class="bg-black/5 px-4 py-4 rounded-md text-sm" type="date" name="end_date" value="{{ request.GET.end_date }}" class="px-4 py-2 rounded-md border mb-4" required />
  
          <button type="submit" class="px-6 py-4 text-sm font-bold bg-blue-400 hover:bg-blue-600 text-white rounded-md">Filter</button>
        </form>
      </div>
  
      <div class="mb-8">
        <form class="relative" action="{% url 'view-events' %}">
          <input class="w-full lg:w-[400px] bg-black/5 p-4 rounded-md focus:border-none focus:outline-none" type="text"
          name="search" placeholder="Search by name or location" value="{{ request.GET.search }}">
          <button type="submit" class="px-4 py-4 bg-blue-400 hover:bg-blue-600 text-white rounded-md absolute right-0">Search</button>
        </form>
      </div>
    </div>

    {% comment %} Events Card {% endcomment %}
    <div class="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-12">
      {% for event in events %}
      <div>
        <a href="{% url "view-event-details" event.id %}" class="cursor-pointer">
          <div class="relative">
              <span class="absolute top-0 left-0 bg-red-500 text-[12px] text-white text-center font-semibold rounded-md m-1 px-2 py-1">Event Type: {{ event.category.get_category_name_display }}</span>
              <span class="absolute top-7 left-0 bg-red-500 text-[12px] text-white text-center font-semibold rounded-md m-1 px-2 py-1">{{ event.total_participants }} People are Joining</span>
              <span class="absolute w-[3px] h-[40px] bg-red-500 -bottom-4 left-1/2 z-10"></span>
              <span class="text-center text-white text-sm font-medium absolute bottom-10 z-20 left-1/2 -translate-x-1/2">{{ event.date|date:"F j Y" }}, <br> {{ event.time }}</span>
              <img class="mx-auto" src="{% static "images/event_1.jpg" %}" alt="">
              <!-- Top Shadow Overlay -->
              <div class="absolute bottom-0 left-0 w-full h-1/3 bg-gradient-to-t from-black/60 to-transparent"></div>
            </div>
            <div class="mt-8">
              <h1 class="text-xl font-medium text-center">
                {% if event.name|length > 20 %}
                  {{ event.name|slice:":20" }}..
                {% else %}
                  {{ event.name }}
                {% endif %}
              </h1>
              <p class="flex gap-4 items-center justify-center mt-2">
                <span><img src="{% static 'images/location.png' %}" alt=""></span>
                <span class="text-[12px] text-[#222222] font-semibold">{{ event.location }}</span>
              </p>
            </div>
        </a>
        <span class="flex gap-1 justify-center mt-4 text-white">
          <a href={% url "update-event" event.id %} class="bg-green-400 flex justify-center p-2 rounded-md cursor-pointer">
            Update
          </a>
          <form method="POST" action="{% url "delete-event" event.id %}">
            {% csrf_token %}
            <button type="submit" class="bg-red-400 flex justify-center p-2 rounded-md cursor-pointer">
              Delete
            </button>
          </form>
        </span>
      </div>
      {% endfor %}
    </div>
  </section>
{% endblock templates %}

events/templates/pages/view-event-details.html
{% extends "index.html" %}
{% load static %}

{% block templates %}
  <div class="w-full">
    <div class="flex flex-col md:flex-row justify-between gap-12">
      {% comment %} Event Details {% endcomment %}
      <div class="md:w-[70%] bg-[#f7f7f7] p-6 rounded-md">
        <img class="rounded-md w-full" src="{% static "images/details.jpg" %}" alt="">
        <div class="flex justify-between items-center">
          <h1 class="my-6 text-2xl font-bold">{{ event.name }}</h1>
          <form method="POST" action="{% url 'register-participant' event.id %}">
            {% csrf_token %}
            <button type="submit" class="bg-green-400 hover:bg-green-700 cursor-pointer px-4 py-2 rounded-md">Register</button>
          </form>
        </div>
        <p class="flex gap-3 mt-2">
          <span><img src="{% static 'images/calender.png' %}" alt=""></span>
          <span class="text-[12px] text-[#222222] font-semibold"> {{event.date}}, {{ event.time }}</span>
        </p>
        <p class="flex gap-3 items-center mt-3">
          <span><img src="{% static 'images/location.png' %}" alt=""></span>
          <span class="text-[12px] text-[#222222] font-semibold">{{ event.location }}</span>
        </p>
        <p class="mt-6 text-black/70 text-sm">
          {{ event.description }}
        </p>
      </div>
      {% comment %} Similar Date Events {% endcomment %}
      <div class="md:w-[30%]">
        <h1 class="mb-6 font-bold text-xl uppercase">Events on the Same Date</h1>
        <div class="grid grid-cols-1 gap-4">
          {% for event in similar_events %}
            {% if event %}
              <a href="{% url "view-event-details" event.id %}">
                <div class="flex gap-4 border p-2 rounded-md">
                  <div>
                    <img width="90" height="40" src="{% static "images/similar.jpg" %}" alt="">
                  </div>
                  <div>
                    <p class="text-sm font-medium">{{ event.name }}</p>
                    <p class="text-red-500 text-[12px] font-bold">{{ event.date }}</p>
                  </div>
                </div>
              </a>
            {% endif %}
            {% empty %}
              <p class="bg-red-100 p-2 text-center rounded-md w-full">No other events on this day.</p>
          {% endfor %}
        </div>
      </div>
    </div>
    {% comment %} Participant Table {% endcomment %}
    <div class="mt-12">
      <h1 class="mb-6 font-bold text-xl uppercase">Here are the list of participants who are joining the event:</h1>
      <div class="relative overflow-x-auto">
        <table class="w-full text-sm text-left text-gray-500">
          <thead class="text-xs text-gray-700 uppercase bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3">
                  Participant Name
              </th>
              <th scope="col" class="px-6 py-3">
                  Email
              </th>
            </tr>
          </thead>
          <tbody>
            {% for p in event.registered_event.all %}
              <tr class="bg-white border-b border-gray-200">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
                    {{ p.participant_name }}
                </th>
                <td class="px-6 py-4">
                    {{ p.participant_email }}
                </td>
              </tr>
            {% empty %}
              <tr>
                <td colspan="2" class="px-6 py-4 text-center text-gray-500">
                    No participants are joining this event.
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock templates %}